(self.AMP=self.AMP||[]).push({n:"amp-lightbox",v:"1533168552513",f:(function(AMP,_){var f;function m(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function n(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ba=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function p(a){var b=Object.create(null);if(!a)return b;for(var c;c=ba.exec(a);){var d=n(c[1],c[1]),e=c[2]?n(c[2],c[2]):"";b[d]=e}return b};var q="";self.log=self.log||{user:null,dev:null,userForEmbed:null};var r=self.log;var ca=Object.prototype.hasOwnProperty;function t(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function u(a){return a||{}};function v(a,b){a=a.__AMP_TOP||a;return w(a,b)}function x(a){var b=y(a),b=z(b);return w(b,"history")}function A(a,b){a=y(a);a=z(a);return w(a,b)}function y(a){return a.nodeType?v((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function z(a){a=y(a);return a.isSingleDoc()?a.win:a}function w(a,b){B(a,b);var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function B(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function da(a,b){for(var c,d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null}function ea(a){return a.closest?a.closest(".i-amphtml-fie"):da(a,function(a){var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return b?b.call(a,".i-amphtml-fie"):!1})};var C,D="Webkit webkit Moz moz ms O o".split(" ");function E(a,b,c){if(2>b.length?0:0==b.lastIndexOf("--",0))return b;C||(C=t());var d=C[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var g=0;g<D.length;g++){var h=D[g]+e;if(void 0!==a[h]){e=h;break a}}e=""}var k=e;void 0!==a[k]&&(d=k)}c||(C[b]=d)}return d}function F(a,b,c){var d;(b=E(a.style,b,void 0))&&(a.style[b]=d?c+d:c)}function G(a,b){for(var c in b)F(a,c,b[c])}
function fa(a){var b=["display"],c={};b.forEach(function(a){c[a]=null});G(a,c)};function H(){this.l=null}f=H.prototype;f.add=function(a){var b=this;this.l||(this.l=[]);this.l.push(a);return function(){b.remove(a)}};f.remove=function(a){this.l&&(a=this.l.indexOf(a),-1<a&&this.l.splice(a,1))};f.removeAll=function(){this.l&&(this.l.length=0)};f.fire=function(a){if(this.l)for(var b=this.l,c=0;c<b.length;c++)(0,b[c])(a)};f.getHandlerCount=function(){return this.l?this.l.length:0};function ga(a,b){function c(){d=0;var h=500-(a.Date.now()-e);if(0<h)d=a.setTimeout(c,h);else{var k=g;g=null;b.apply(null,k)}}var d=0,e=0,g=null;return function(b){for(var k=[],l=0;l<arguments.length;++l)k[l-0]=arguments[l];e=a.Date.now();g=k;d||(d=a.setTimeout(c,500))}};function ha(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};function I(a,b,c){var d=this;this.ra=v(a,"timer");this.va=b;this.ua=c||0;this.J=-1;this.$=0;this.ea=!1;this.sa=function(){return d.T()}}I.prototype.isPending=function(){return-1!=this.J};I.prototype.schedule=function(a){var b=a||this.ua;this.ea&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.$?(this.cancel(),this.$=c,this.J=this.ra.delay(this.sa,b),!0):!1};I.prototype.T=function(){this.J=-1;this.$=0;this.ea=!0;this.va();this.ea=!1};
I.prototype.cancel=function(){this.isPending()&&(this.ra.cancel(this.J),this.J=-1)};function ia(a,b,c){var d=Date.now();this.type=a;this.data=b;this.time=d;this.event=c}
function J(a,b){this.w=a;this.c=[];this.C=[];this.m=[];this.h=[];this.j=null;this.Aa=b;this.V=!1;this.T=new I(a.ownerDocument.defaultView,this.ma.bind(this));this.oa=new H;this.I=Object.create(null);this.la=this.za.bind(this);this.ja=this.xa.bind(this);this.ka=this.ya.bind(this);this.ia=this.wa.bind(this);this.w.addEventListener("touchstart",this.la);this.w.addEventListener("touchend",this.ja);this.w.addEventListener("touchmove",this.ka);this.w.addEventListener("touchcancel",this.ia);this.aa=!1}
function ja(a){var b;b=void 0===b?!1:b;var c=a.__AMP_Gestures;c||(c=new J(a,b),a.__AMP_Gestures=c);return c}f=J.prototype;f.cleanup=function(){this.w.removeEventListener("touchstart",this.la);this.w.removeEventListener("touchend",this.ja);this.w.removeEventListener("touchmove",this.ka);this.w.removeEventListener("touchcancel",this.ia);delete this.w.__AMP_Gestures;this.T.cancel()};f.onGesture=function(a,b){var c=new a(this),d=c.getType(),e=this.I[d];e||(this.c.push(c),e=new H,this.I[d]=e);return e.add(b)};
f.removeGesture=function(a){var b=(new a(this)).getType();if(a=this.I[b]){a.removeAll();a=ha(this.c,function(a){return a.getType()==b});if(0>a)return!1;this.c.splice(a,1);this.m.splice(a,1);this.h.splice(a,1);this.C.splice(a,1);delete this.I[b];return!0}return!1};f.onPointerDown=function(a){return this.oa.add(a)};
f.za=function(a){var b=Date.now();this.V=!1;this.oa.fire(a);for(var c=0;c<this.c.length;c++)if(!this.m[c]&&(this.h[c]&&this.h[c]<b&&K(this,c),this.c[c].onTouchStart(a))){var d=c;this.C[d]=!0;this.h[d]=0}L(this,a)};f.ya=function(a){for(var b=Date.now(),c=0;c<this.c.length;c++)this.C[c]&&(this.h[c]&&this.h[c]<b?K(this,c):this.c[c].onTouchMove(a)||K(this,c));L(this,a)};
f.xa=function(a){for(var b=Date.now(),c=0;c<this.c.length;c++)this.C[c]&&(this.h[c]&&this.h[c]<b?K(this,c):(this.c[c].onTouchEnd(a),(!this.h[c]||this.h[c]<b)&&K(this,c)));L(this,a)};f.wa=function(a){for(var b=0;b<this.c.length;b++){var c=b;this.m[c]=0;K(this,c)}L(this,a)};function L(a,b){var c=!!a.j||a.V;a.V=!1;if(!c)for(var d=Date.now(),e=0;e<a.c.length;e++)if(a.m[e]||a.h[e]&&a.h[e]>=d){c=!0;break}c&&(b.stopPropagation(),a.Aa||b.preventDefault());a.aa&&(a.aa=!1,a.ma())}
f.ma=function(){for(var a=Date.now(),b=-1,c=0;c<this.c.length;c++)if(!this.m[c])this.h[c]&&this.h[c]<a&&K(this,c);else if(-1==b||this.m[c]>this.m[b])b=c;if(-1!=b){for(var d=0,c=0;c<this.c.length;c++)!this.m[c]&&this.C[c]&&(d=Math.max(d,this.h[c]-a));if(2>d){for(var a=b,c=this.c[a],e=0;e<this.c.length;e++)if(e!=a){var g=e;this.m[g]=0;K(this,g)}this.m[a]=0;this.h[a]=0;this.j=c;c.acceptStart()}else this.T.schedule(d)}};function K(a,b){a.C[b]=!1;a.h[b]=0;a.m[b]||a.c[b].acceptCancel()}
function M(a,b){this.Ba=a;this.S=b}f=M.prototype;f.getType=function(){return this.Ba};f.signalReady=function(a){var b=this.S;if(b.j)this.acceptCancel();else{for(var c=Date.now(),d=0;d<b.c.length;d++)b.c[d]==this&&(b.m[d]=c+a,b.h[d]=0);b.aa=!0}};f.signalPending=function(a){var b=this.S;if(b.j)this.acceptCancel();else for(var c=Date.now(),d=0;d<b.c.length;d++)b.c[d]==this&&(b.h[d]=c+a)};f.signalEnd=function(){var a=this.S;a.j==this&&(a.j=null,a.V=!0)};
f.signalEmit=function(a,b){var c=this.S.I[this.getType()];c&&c.fire(new ia(this.getType(),a,b))};f.acceptStart=function(){};f.acceptCancel=function(){};f.onTouchStart=function(){return!1};f.onTouchMove=function(){return!1};f.onTouchEnd=function(){};function N(a,b,c){1>b&&(b=1);var d=a/b,e=.5+Math.min(b/33.34,.5);return d*e+c*(1-e)};function O(a,b,c,d){M.call(this,a,b);this.P=c;this.U=d;this.j=!1;this.F=this.D=this.ba=this.R=this.qa=this.da=this.ca=this.H=this.G=this.L=this.K=0}m(O,M);f=O.prototype;f.onTouchStart=function(a){return(a=a.touches)&&1==a.length?(this.qa=Date.now(),this.K=a[0].clientX,this.L=a[0].clientY,!0):!1};
f.onTouchMove=function(a){var b=a.touches;if(b&&1==b.length){var c=b[0],b=c.clientX,c=c.clientY;this.G=b;this.H=c;if(this.j)P(this,!1,!1,a);else if(a=Math.abs(b-this.K),b=Math.abs(c-this.L),this.P&&this.U)(8<=a||8<=b)&&this.signalReady(-10);else if(this.P)if(8<=a&&a>b)this.signalReady(-10);else{if(8<=b)return!1}else if(this.U)if(8<=b&&b>a)this.signalReady(-10);else{if(8<=a)return!1}else return!1;return!0}return!1};f.onTouchEnd=function(a){this.j&&(this.j=!1,P(this,!1,!0,a),this.signalEnd())};
f.acceptStart=function(){this.j=!0;this.ca=this.K;this.da=this.L;this.ba=this.qa;this.K=this.G;this.L=this.H;P(this,!0,!1,null)};f.acceptCancel=function(){this.j=!1};function P(a,b,c,d){a.R=Date.now();var e=a.R-a.ba;if(!c&&4<e||c&&16<e)a.D=N(a.G-a.ca,e,a.D),a.F=N(a.H-a.da,e,a.F),a.D=1E-4<Math.abs(a.D)?a.D:0,a.F=1E-4<Math.abs(a.F)?a.F:0,a.ca=a.G,a.da=a.H,a.ba=a.R;a.signalEmit({first:b,last:c,time:a.R,deltaX:a.P?a.G-a.K:0,deltaY:a.U?a.H-a.L:0,velocityX:a.P?a.D:0,velocityY:a.U?a.F:0},d)}
function Q(a){O.call(this,"swipe-xy",a,!0,!0)}m(Q,O);var R={"fade-in":{openStyle:u({opacity:1}),closedStyle:u({opacity:0}),durationSeconds:.1},"fly-in-bottom":{openStyle:u({transform:"translate(0, 0)"}),closedStyle:u({transform:"translate(0, 100%)"}),durationSeconds:.3},"fly-in-top":{openStyle:u({transform:"translate(0, 0)"}),closedStyle:u({transform:"translate(0, -100%)"}),durationSeconds:.3}};
function S(a){var b;b=AMP.BaseElement.call(this,a)||this;b.ga=null;b.o=null;b.ha=null;b.X=null;b.Z=-1;b.M=!1;b.O=null;b.B=!1;b.A=0;b.na=0;b.Y=0;b.fa=null;b.N=(a.getAttribute("animate-in")||"fade-in").toLowerCase();b.W=ga(b.win,function(){var a=b.o;b.scheduleLayout(a);b.scheduleResume(a)});return b}m(S,AMP.BaseElement);f=S.prototype;
f.buildCallback=function(){this.user().assert(ca.call(R,this.N),"Invalid `animate-in` value %s",this.N);this.element.classList.add("i-amphtml-overlay");var a;a:{a=this.element;if(a.nodeType){var b=(a.ownerDocument||a).defaultView;if(b=b!=(b.__AMP_TOP||b)&&B(b,"action")?w(b,"action"):null){a=b;break a}}a=A(a,"action")}this.ha=a;a=this.win;ea(this.element)&&T(a,a.document.body);this.registerAction("open",this.activate.bind(this));this.registerAction("close",this.close.bind(this))};
function U(a){V(a,!0).forEach(function(b){a.setAsOwner(b)})}function V(a,b){if(!a.X||b){var c;if(c=a.element.getElementsByClassName("i-amphtml-element")){for(var d=Array(c.length),e=0;e<c.length;e++)d[e]=c[e];c=d}else c=[];a.X=c}return a.X}
function ka(a){if(!a.o){var b=a.element;a.B=b.hasAttribute("scrollable");var c=a.getRealChildren();a.o=b.ownerDocument.createElement("div");a.B||a.applyFillContent(a.o);b.appendChild(a.o);c.forEach(function(b){a.o.appendChild(b)});a.B&&(U(a),b.classList.add("i-amphtml-scrollable"),b.addEventListener("amp:dom-update",function(){U(a);W(a,a.A,a.A)}),b.addEventListener("scroll",a.pa.bind(a)));if(!a.B){var d=ja(b);d.onGesture(Q,function(){})}}}f.layoutCallback=function(){return Promise.resolve()};
f.activate=function(){var a=this;this.M||(ka(this),this.O=this.ta.bind(this),this.win.document.documentElement.addEventListener("keydown",this.O),this.getViewport().enterLightboxMode(this.element).then(function(){return la(a)}))};function ma(a){var b=a.o.querySelector("[autofocus]");if(b)try{b.focus()}catch(c){}}
function la(a){var b=a.element,c=R[a.N],d=c.durationSeconds,e=c.openStyle,g=c.closedStyle,h=Object.keys(e).map(function(a){return a+" "+d+"s ease-in"}).join(",");a.Y++;a.B&&F(b,"webkitOverflowScrolling","touch");G(b,u({transition:h}));G(b,g);fa(b);a.mutateElement(function(){b.scrollTop=0});ma(a);a.mutateElement(function(){G(b,e)});c=a.o;a.B?(a.pa(),W(a,a.A,a.A)):a.updateInViewport(c,!0);b.addEventListener("transitionend",a.W);b.addEventListener("animationend",a.W);a.scheduleLayout(c);a.scheduleResume(c);
X(a,"lightboxOpen");x(a.getAmpDoc()).push(a.close.bind(a)).then(function(b){a.Z=b});a.M=!0}f.ta=function(a){27==a.keyCode&&this.close()};f.close=function(){var a=this;this.M&&(this.B&&F(this.element,"webkitOverflowScrolling",""),this.getViewport().leaveLightboxMode(this.element).then(function(){return na(a)}))};
function na(a){function b(){d==a.Y&&(a.collapse(),a.W())}var c=a.element;G(c,R[a.N].closedStyle);var d=++a.Y;c.addEventListener("transitionend",b);c.addEventListener("animationend",b);-1!=a.Z&&x(a.getAmpDoc()).pop(a.Z);a.win.document.documentElement.removeEventListener("keydown",a.O);a.O=null;a.schedulePause(a.o);a.M=!1;X(a,"lightboxClose")}f.pa=function(){var a=this.element.scrollTop||1;this.A=this.element.scrollTop=a;null===this.fa&&Y(this,a)};
function Y(a,b){a.fa=v(a.win,"timer").delay(function(){if(30>Math.abs(b-a.A)){a.fa=null;var c=a.A;W(a,c,a.na);a.na=c;a.A=c}else Y(a,a.A)},100)}function W(a,b,c){var d=[];Z(a,b,function(b){d.push(b);a.updateInViewport(b,!0);a.scheduleLayout(b)});c!=b&&Z(a,c,function(b){d.includes(b)||a.updateInViewport(b,!1)})}
function Z(a,b,c){a.ga||(a.ga={width:a.element.clientWidth,height:a.element.clientHeight});for(var d=a.ga.height,e=V(a),g=0;g<e.length;g++){for(var h=e[g],k=0,l=h;l&&a.element.contains(l);l=l.offsetParent)k+=l.offsetTop;var aa=2*d;k+h.offsetHeight>=b-aa&&k<=b+aa&&c(h)}}
function X(a,b){var c;var d=a.win;c="amp-lightbox."+b;var e=u({}),g={detail:e};Object.assign(g,void 0);"function"==typeof d.CustomEvent?c=new d.CustomEvent(c,g):(d=d.document.createEvent("CustomEvent"),d.initCustomEvent(c,!!g.bubbles,!!g.cancelable,e),c=d);a.ha.trigger(a.element,b,c,100)}
function T(a,b){var c={},d=v(a,"ampdoc").getAmpDoc();A(d,"resources").measureMutateElement(b,function g(){c.alreadyTransparent="rgba(0, 0, 0, 0)"==(a.getComputedStyle(b)||t())["background-color"]},function h(){if(!c.alreadyTransparent){if(!r.user)throw Error("failed to call initLogConstructor");r.user.warn("amp-lightbox","The background of the <body> element has been forced to transparent. If you need to set background, use an intermediate container.")}var a={background:"transparent"},d;for(d in a)b.style.setProperty(E(a,
d),a[d].toString(),"important")})}
(function(a){var b=self;if(b.AMP_MODE)b=b.AMP_MODE;else{var c=p(b.location.originalHash||b.location.hash),d=p(b.location.search);q||(q=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"011533168552513");b=b.AMP_MODE={localDev:!1,development:!("1"!=c.development&&!b.AMP_DEV_MODE),examiner:"2"==c.development,filter:c.filter,geoOverride:c["amp-geo"],minified:!0,lite:void 0!=d.amp_lite,test:!1,log:c.log,version:"1533168552513",rtvVersion:q}}"inabox"==b.runtime&&T(window,document.body);
a.registerElement("amp-lightbox",S,"amp-lightbox{display:none;position:fixed!important;z-index:1000;top:0!important;left:0!important;bottom:0!important;right:0!important}amp-lightbox[scrollable]{overflow-y:auto!important;overflow-x:hidden!important}\n/*# sourceURL=/extensions/amp-lightbox/0.1/amp-lightbox.css*/")})(self.AMP);
})});
//# sourceMappingURL=amp-lightbox-0.1.js.map

